version: "2"
services:
  app:
    build: ./app
    image: acts:latest
    links:
      - db
    ports:
      - "80:80"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
